import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";


const editUndoBrk = localFont({
  src: '../public/edit-undo.brk.ttf',
  variable: '--font-editundo'
})

const pixelOperator8 = localFont({
  src: '../public/PixelOperator8.ttf',
  variable: '--font-pixel'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${editUndoBrk.variable} ${pixelOperator8.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
